### ISSUE TITLE
Adding kotlinx-coroutines-core as a dependency

### ISSUE THREAD

**Issue by yoavschechter** [Foso/gtvmonkey-scripts#2]
Thanks for the template, very helpful.
I added these 2 lines to the Gradle dependencies block:
```
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.3'
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core-js:1.4.3'
```
and changed the main function to:
```
suspend fun main() {
    val response = window.fetch("https://github.com/", RequestInit(method = "GET")).await()
}
```

Then executed the build task, which completed successfully. But when the script tries to run, I get:
`Error: Error loading module 'gtvmonkey'. Its dependency 'kotlinx-coroutines-core' was not found. Please, check whether 'kotlinx-coroutines-core' is loaded prior to 'gtvmonkey'.`

How do I fix this?

**Comment by Foso** [comment]
Hi @yoavschechter thank you for reporting this. My gradle task was using the wrong js file, where the coroutines js file was not included. I changed the task and it should be working now.
