### ISSUE TITLE
why does it require Android SDK?

### ISSUE THREAD

**Issue by shalva97** [Foso/gtvmonkey-scripts#3]
just pulled the project but gradle is telling me to install Android SDK.
![image](https://user-images.githubusercontent.com/22417494/128409991-c6477039-d126-4624-9bf9-8bf444dd3ea1.png)
hows that even possible, im on Intellij IDEA

**Comment by Foso** [comment]
Hi @shalva97 , i guess it was because of my local.properties file. I removed that file

**Comment by shalva97** [comment]
thx it worked
